@startuml
    entity Game{
        <<PK>> gameID [NUMBER]
        --
        date [DATE]
    }

    entity playedGames{
        <<FK>> gameID[NUMBER]
        <<FK>> teamID[NUMBER]
    }

    entity Team{
        <<PK>> teamID [NUMBER]
        --
        teamName [VARCHAR]
    }

    entity Player{
        <<PK>> playerID [NUMBER]
        <<FK>> teamID [NUMBER]
        --
        name [VARCHAR]
    }

    entity Stage{
        <<PK>> stageID[NUMBER]
        <<FK>> gameID[NUMBER]
    }

    entity Score{
        <<FK>> teamId[NUMBER]
        <<FK>> stageId[NUMBER]
        --
        score[NUMBER]
    }



    Team||--o{playedGames
    Game||--o{playedGames
    Stage}|-||Game
    Team||-|{Player
    Score}|--||Stage
    Score}|--||Team

@enduml