@startuml
    entity Game{
        <<PK>> gameID [NUMBER]
        --
        date [DATE]
    }

    entity Game_Team{
        <<FK>> gameID[NUMBER]
        <<FK>> teamID[NUMBER]
    }

    entity Team{
        <<PK>> teamID [NUMBER]
        --
        name [VARCHAR]
    }

    entity Player{
        <<PK>> playerId [NUMBER]
        <<FK>> teamId [NUMBER]
        --
        name [VARCHAR]
    }

    entity Stage{
        <<PK>> stageId[NUMBER]
        <<FK>> gameId[NUMBER]
        --
        stagenumber[NUMBER]
    }

    entity Turn {
        <<PK>> turnId[NUMBER]
        <<FK>> stageId[NUMBER]]
    }

    entity Score{
        <<PK>> scoreId[NUMBER]
        <<FK>> teamId[NUMBER]
        <<FK>> turnId[NUMBER]
        --
        score[NUMBER]
    }

    Team||--o{Game_Team
    Game||--o{Game_Team
    Stage}|-||Game
    Team||-|{Player
    Score}|--||Team
    Score}|--||Turn
    Stage}|--||Turn
@enduml