@header = http://localhost:8080/api/

###
### TEAM
###
GET http://localhost:8080/api/team/createTeam?teamName=TestTeam
Content-Type: */*
###
GET http://localhost:8080/api/team/15
###
GET http://localhost:8080/api/teams/0
###
GET http://localhost:8080/api/team/findTeamByName?teamName=Lehrer
###
GET {{header}}team/getAllGamesOfTeam?teamId=1
###
POST {{header}}team/renameTeam?teamId=1&newName=Anfänger
Content-Type: */*
###
### GAME
###
GET {{header}}games/createGame
Content-Type: */*
###
GET {{header}}games/getAllGames
###
GET {{header}}games/findGameById?gameId=1
###
POST {{header}}games/addTeamToGame?gameId=1&teamId=1
###
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "name": "Empty Team Group",
  "teams": [],
  "games": []
}
###
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "name": "Spielgruppe Eispunkt",
  "teams": [
    {
      "name": "ÖTSU Oepping 1"
    },
    {
      "name": "ATSV Waldneukirchen Stocksport 1"
    }
  ],
  "games": []
}
###
POST http://localhost:8080/api/team?teamName=test
Content-Type: application/json

###
POST http://localhost:8080/api/games
Content-Type: application/json

{

}

###

PUT http://localhost:8080/api/tournaments
Content-Type: application/json

{
    "tournamentId": 1,
    "name": "Testing",
    "location": "None"
}


###

DELETE http://localhost:8080/api/teams/1


###

PATCH http://localhost:8080/api/teams/isVisible/1
