@header = http://localhost:8080/api/

###
### TEAM
###
GET http://localhost:8080/api/team/createTeam?teamName=TestTeam
Content-Type: */*
###
GET http://localhost:8080/api/team/getAllTeams
###
GET http://localhost:8080/api/team/findTeamById?teamId=1
###
GET http://localhost:8080/api/team/findTeamByName?teamName=Lehrer
###
GET {{header}}team/getAllGamesOfTeam?teamId=1
###
POST {{header}}team/renameTeam?teamId=1&newName=Anfänger
Content-Type: */*
###
### GAME
###
GET {{header}}games/createGame
Content-Type: */*
###
GET {{header}}games/getAllGames
###
GET {{header}}games/findGameById?gameId=1
###
POST {{header}}games/addTeamToGame?gameId=1&teamId=1
###
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "name": "Empty Team Group",
  "teams": [],
  "games": []
}
###
POST http://localhost:8080/api/groups
Content-Type: application/json

{
  "name": "Spielgruppe Eispunkt",
  "teams": [
    {
      "name": "ÖTSU Oepping 1"
    },
    {
      "name": "ATSV Waldneukirchen Stocksport 1"
    }
  ],
  "games": []
}