services:
  db:
    container_name: eispunkt-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - eispunkt-net
    environment:
      - POSTGRES_PASSWORD=eispunkt#4040#
      - POSTGRES_USER=admin
      - POSTGRES_DB=eispunkt

  backend:
    container_name: eispunkt-backend
    build:
      context: ../backend
    ports:
      - "8081:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/eispunkt
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=eispunkt#4040#
    depends_on:
      - db
    networks:
      - eispunkt-net

  frontend:
    container_name: eispunkt-frontend
    build:
      context: ../frontend/eispunkt-svelteKit
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - eispunkt-net

volumes:
  postgres:

networks:
  eispunkt-net:
    driver: bridge
