services:
  postgres:
    container_name: eispunkt-db
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - eispunkt-net
    environment:
      - POSTGRES_PASSWORD=eispunkt#4040#
      - POSTGRES_USER=admin
      - POSTGRES_DB=eispunkt


  app:
    container_name: eispunkt-app
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/eispunkt
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=eispunkt#4040#
    depends_on:
        - postgres
    networks:
        - eispunkt-net

volumes:
  postgres:

networks:
  eispunkt-net:
    driver: bridge