@startwbs
title Eispunkt Stundeneinteilung 2025/26

* Eispunkt (700h)
** Backend (200h)
*** Florian (150h)
*** Marvin (50h)
** Frontend (350h)
*** Marvin (50h)
*** Atilla (150h)
*** Vanesa (150h)
** Projektmanagement (50h)
*** Florian
** Deployment (100h)
*** Marvin

right footer Marvin Anderson 6.10.25
@endwbs
